### ISSUE TITLE
Approved Revisions related properties to not update after initial annotation

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticExtraSpecialProperties#108]
### Setup and configuration

- SMW version: 2.5.6
- SESP version: 2.0.0-alpha (bcd3a4c) 07:51, 5 July 2018
- MW version: 1.30.0 (830bb58)
- PHP version: 5.6.38 (apache2handler)
- DB (MySQL etc. and version): 5.5.60-MariaDB

**- Approved Revs version: 0.8.0 (f8fd2a2) 11:59, 16 May 2017 (MEZA)**

### Issue

SESP Properties for Approved Revisions do not update after population from first approval. all AR SESP properties are fixed. Only way to get them to be accurate again is to run the rebuildData.php SM maintenance script with the --f option for force a purge.

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
1. make a new page titled XYZ
2. open "browse properties" of page XYZ in a new tab
3. verify that no AR properties are displayed (this is correct behavior for a new un-approved page
4. open "view history" of page XYZ in a new tab
5. make a few edits to create the history
6. refresh history to see history
7. on history page, click approve on a revision in the middle of the edit history
8. refresh page XYZ and see that the page is 'approved'
9. refresh "browse properties" of page XYZ and verify that the AR properties appear correctly
10. unapprove the revision and revisit "browse properties" of page XYZ
11. verify that AR properties are stuck at old values when they should be gone because the page is not approved anymore.
11a - run runJobs.php and verify that it is not waiting for any jobs to execute
11b - purge the page and verify that it is not simply a page cache issue.
12. run rebuildData,php --f and then run runJobs.php
13. verify that SESP data is now correct.

**Comment by kghbln** [comment]
Can this also be observed with SMW 3.0.0 and SESP 2.0.0? @hexmode FYI

**Comment by hexmode** [comment]
> @hexmode FYI

Thanks.  I asked Rich to submit this here.

@revansx could you try reproducing this on the newer SMW and SESP as Karsten suggested?

**Comment by revansx** [comment]
well.. it will have to wait until I upgrade to those in Dec. I'm planning to upgrade my whole meza application to 31.x  over the holiday. 

The procedure I wrote above is simple. Can one of you with SMW 3.0.0 and SESP 2.0.0 try it? If you say that the problem doesn't exist with SMW 3.0.0 and SESP 2.0.0, then I may be motivated to upgrade sooner to get the good results.

**Comment by revansx** [comment]
this seems similar to my observed issue:
https://www.mediawiki.org/wiki/Topic:Rphkgpatqhf9ozp7

**Comment by kghbln** [comment]
I will add Approved Revisions to the sandbox wiki in about a fortnight for you to demonstrate the issue for the current software version since there will not be fixes to SMW 2.5.x and SESP 1.5.x in any case. Please ping me in case I forget to do this.

**Comment by revansx** [comment]
ok. please do. IN about a fortnight I will probably have upgraded to the latest versions of SMW and SESP and so it may be moot. But I think it would be wise to have AR on the sandbox regardless. I'll set a timer ;-) .. thanks!

**Comment by kghbln** [comment]
It took me longer. :(  Now implemented with

```
## ApprovedRevs
wfLoadExtension( 'ApprovedRevs' );
$egApprovedRevsEnabledNamespaces[NS_MAIN] = false;
$egApprovedRevsEnabledNamespaces[NS_USER] = false;
$egApprovedRevsEnabledNamespaces[NS_FILE] = false;
$egApprovedRevsEnabledNamespaces[NS_TEMPLATE] = false;
$egApprovedRevsEnabledNamespaces[NS_HELP] = false;
$egApprovedRevsEnabledNamespaces[NS_EXTRA] = false;
$egApprovedRevsAutomaticApprovals = false;
$egApprovedRevsShowApproveLatest = true;
$wgGroupPermissions['*']['viewlinktolatest'] = false;
$wgGroupPermissions['user']['viewlinktolatest'] = true;
$wgGroupPermissions['approver']['approverevisions'] = true;
$wgGroupPermissions['sysop']['approverevisions'] = false;
```

**Comment by revansx** [comment]
Aye, aye! o7 .. ty

**Comment by mwjames** [comment]
I added two hooks [0, 1] (see attached notes) to make sure users that rely on non MW specific revision management can implement some extra control especially when manipulating revision state because SMW-core and its default behaviour [2] only cares for information available in `LinksUpdate` and does not cater for any manipulation outside of the MW framework.

[1] should provide some inspiration on how to get started, whether this works with the new MCR (due to use of `Revision::newFromId`) I don't know.

> SESP Properties for Approved Revisions do not update after population from first approval.

I haven't tested [1] against `Approved Revisions` properties but it should follow the same update logic as any other annotation value whether set manually (by a user) or automatic.

This topic now came up several times, and I'm implore that interested parties create a wiki page, describe the use case, and add the necessary links, so I won't have to answer similar questions in future.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3032
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/code-snippets/approve.update.md
[2] SMW always chooses the latest available revision to represent its data.

**Comment by mwjames** [comment]
Discussion about ApprovedRevs as topic of should continue at https://github.com/SemanticMediaWiki/SemanticApprovedRevs.

I would expect that all properties related to `ApprovedRevs` are moved from this repo into the `SemanticApprovedRevs` before a release to isolate access to the `ApprovedRevs` extension thereby minimize the maintenance and in case interfaces break, they are going to break only in one place.
