### ISSUE TITLE
SESP breaks Resource Loader

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticExtraSpecialProperties#129]
### Setup and configuration

Product|Version|License|Description|Authors
--|--|--|--|--
Semantic MediaWiki | 3.1.0 | GPL-2.0-or-later | Делает вашу вики более доступной — для машин и людей (документация в сети) | Markus Krötzsch, Jeroen De Dauw, James Hong Kong и другие
Semantic Extra Special Properties | 2.0.0 | GPL-2.0-or-later | Добавляет некоторые дополнительные специальные свойства для всех страниц | James Hong Kong, Leo Wallentin и другие

Product|Version
--|--
MediaWiki | 1.31.3 (8af9c78)01:21, 5 ноября 2019
PHP | 7.2.24-0ubuntu0.18.04.1 (fpm-fcgi)
MariaDB | 10.3.18-MariaDB-1:10.3.18+maria~bionic-log

### Issue

When I was trying to investigate why _Semantic Glossary_ stopped to produce popups after upgrading to SMW 3.1, I found in my browser console:
```
[7cf91b206d0c705d1e3a9f13] /w/load.php?debug=false&lang=ru&modules=startup&only=scripts&skin=timeless   BadMethodCallException from line 848 of /var/www/wiki/w/includes/session/SessionManager.php: Sessions are disabled for this entry point
Backtrace:
#0 /var/www/wiki/w/includes/session/SessionManager.php(196): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
#1 /var/www/wiki/w/includes/WebRequest.php(736): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#2 /var/www/wiki/w/includes/user/User.php(1350): WebRequest->getSession()
#3 /var/www/wiki/w/includes/user/User.php(449): User->loadFromSession()
#4 /var/www/wiki/w/includes/user/User.php(5411): User->load()
#5 /var/www/wiki/w/includes/user/User.php(3101): User->loadOptions()
#6 /var/www/wiki/w/includes/context/RequestContext.php(336): User->getOption(string)
#7 /var/www/wiki/w/includes/StubObject.php(206): RequestContext->getLanguage()
#8 /var/www/wiki/w/includes/StubObject.php(168): StubUserLang->_newObject()
#9 /var/www/wiki/w/includes/StubObject.php(111): StubObject->_unstub(string, integer)
#10 /var/www/wiki/w/includes/StubObject.php(138): StubObject->_call(string, array)
```
**`#11 /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(136): StubObject->__call(string, array)`**
```
#12 /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/PropertyRegistry.php(43): SESP\AppFactory->getPropertyDefinitions()
#13 /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(144): SESP\PropertyRegistry->register(SMW\PropertyRegistry)
#14 /var/www/wiki/w/includes/Hooks.php(177): SESP\HookRegistry->SESP\{closure}(SMW\PropertyRegistry)
#15 /var/www/wiki/w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#16 /var/www/wiki/w/extensions/SemanticMediaWiki/src/PropertyRegistry.php(507): Hooks::run(string, array)
#17 /var/www/wiki/w/extensions/SemanticMediaWiki/src/PropertyRegistry.php(98): SMW\PropertyRegistry->initProperties(array)
#18 /var/www/wiki/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(94): SMW\PropertyRegistry::getInstance()
#19 /var/www/wiki/w/extensions/SemanticMediaWiki/src/DataItemFactory.php(45): SMW\DIProperty->__construct(string, boolean)
#20 /var/www/wiki/w/extensions/SemanticMediaWiki/src/Property/Annotators/EditProtectedPropertyAnnotator.php(71): SMW\DataItemFactory->newDIProperty(string)
#21 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(208): SMW\Property\Annotators\EditProtectedPropertyAnnotator->addTopIndicatorTo(ParserOutput)
#22 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(170): SMW\MediaWiki\Hooks\ParserAfterTidy->addPropertyAnnotations(SMW\Property\AnnotatorFactory, SMW\SemanticData)
#23 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(96): SMW\MediaWiki\Hooks\ParserAfterTidy->performUpdate(string)
#24 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(359): SMW\MediaWiki\Hooks\ParserAfterTidy->process(string)
#25 /var/www/wiki/w/includes/Hooks.php(177): SMW\MediaWiki\Hooks->onParserAfterTidy(Parser, string)
#26 /var/www/wiki/w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#27 /var/www/wiki/w/includes/parser/Parser.php(1428): Hooks::run(string, array)
#28 /var/www/wiki/w/includes/parser/Parser.php(446): Parser->internalParseHalfParsed(string, boolean, boolean)
#29 /var/www/wiki/w/includes/cache/MessageCache.php(1162): Parser->parse(string, Title, ParserOptions, boolean)
#30 /var/www/wiki/w/includes/Message.php(1244): MessageCache->parse(string, Title, boolean, boolean, Language)
#31 /var/www/wiki/w/includes/Message.php(869): Message->parseText(string)
#32 /var/www/wiki/w/includes/Message.php(922): Message->toString(string)
#33 /var/www/wiki/w/extensions/VisualEditor/includes/VisualEditorDataModule.php(30): Message->parse()
#34 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(706): VisualEditorDataModule->getScript(DerivativeResourceLoaderContext)
#35 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(674): ResourceLoaderModule->buildContent(DerivativeResourceLoaderContext)
#36 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(828): ResourceLoaderModule->getModuleContent(DerivativeResourceLoaderContext)
#37 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(665): ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)
#38 [internal function]: ResourceLoader->{closure}(string)
#39 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(678): array_map(Closure, array)
#40 /var/www/wiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(449): ResourceLoader->getCombinedVersion(DerivativeResourceLoaderContext, array)
#41 /var/www/wiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(422): ResourceLoaderStartUpModule->getAllModuleHashes(DerivativeResourceLoaderContext)
#42 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(831): ResourceLoaderStartUpModule->getDefinitionSummary(DerivativeResourceLoaderContext)
#43 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(665): ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)
#44 [internal function]: ResourceLoader->{closure}(string)
#45 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(678): array_map(Closure, array)
#46 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(759): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#47 /var/www/wiki/w/load.php(51): ResourceLoader->respond(ResourceLoaderContext)
#48 {main}
```

**Comment by alex-mashin** [comment]
It seems to me that the problem is caused by _MediaWiki_'s trying to insert parsed messages in user's language into JavaScript, which is supposed not to include any user-, and therefore, session-dependant data.

I presume that PHP code that forms JavaScript files for _ResourceLoader_ must not refer to `$wgLang` as `SemanticExtraSpecialProperties/src/AppFactory.php` does in line 136. However, I am not now sure, which extension to blame: _SESP_ or _VisualEditor_ (version 1.31 im my setup).

**Comment by mwjames** [comment]
> [7cf91b206d0c705d1e3a9f13] /w/load.php?debug=false&lang=ru&modules=startup&only=scripts&skin=timeless   BadMethodCallException from line 848 of /var/www/wiki/w/includes/session/SessionManager.php: Sessions are disabled for this entry point

There is a long history of MW bugs about the same kind of error and
I'm reluctant to see this an issue in either SMW or SESP.

We could try adding a state check to SMW core as __sanity__ check not
as something that would fix above `BadMethodCallException`. Also, it
wouldn't happen this year and most likely only be deployed with SMW
3.2.

The change would entail something like the attached file but I cannot
vouch for it since I'm unable to create a condition that would cause
above exception.

Feel free to apply the diff to SMW core and test this in your environment.

On 11/6/19, Alexander Mashin <notifications@github.com> wrote:
> ### Setup and configuration

>

> Product|Version|License|Description|Authors

> --|--|--|--|--

> Semantic MediaWiki | 3.1.0 | GPL-2.0-or-later | Делает вашу вики более
> доступной — для машин и людей (документация в сети) | Markus Krötzsch,
> Jeroen De Dauw, James Hong Kong и другие

> Semantic Extra Special Properties | 2.0.0 | GPL-2.0-or-later | Добавляет
> некоторые дополнительные специальные свойства для всех страниц | James Hong
> Kong, Leo Wallentin и другие

>

> Product|Version

> --|--

> MediaWiki | 1.31.3 (8af9c78)01:21, 5 ноября 2019

> PHP | 7.2.24-0ubuntu0.18.04.1 (fpm-fcgi)

> MariaDB | 10.3.18-MariaDB-1:10.3.18+maria~bionic-log

>

> ### Issue

>

> When I was trying to investigate why _Semantic Glossary_ stopped to produce
> popups after upgrading to SMW 3.1, I found in my browser console:

> ```

> [7cf91b206d0c705d1e3a9f13]
> /w/load.php?debug=false&lang=ru&modules=startup&only=scripts&skin=timeless
> BadMethodCallException from line 848 of
> /var/www/wiki/w/includes/session/SessionManager.php: Sessions are disabled
> for this entry point

> Backtrace:

> #0 /var/www/wiki/w/includes/session/SessionManager.php(196):
> MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo,
> WebRequest)

> #1 /var/www/wiki/w/includes/WebRequest.php(736):
> MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)

> #2 /var/www/wiki/w/includes/user/User.php(1350): WebRequest->getSession()

> #3 /var/www/wiki/w/includes/user/User.php(449): User->loadFromSession()

> #4 /var/www/wiki/w/includes/user/User.php(5411): User->load()

> #5 /var/www/wiki/w/includes/user/User.php(3101): User->loadOptions()

> #6 /var/www/wiki/w/includes/context/RequestContext.php(336):
> User->getOption(string)

> #7 /var/www/wiki/w/includes/StubObject.php(206):
> RequestContext->getLanguage()

> #8 /var/www/wiki/w/includes/StubObject.php(168):
> StubUserLang->_newObject()

> #9 /var/www/wiki/w/includes/StubObject.php(111): StubObject->_unstub(string,
> integer)

> #10 /var/www/wiki/w/includes/StubObject.php(138): StubObject->_call(string,
> array)

> ```

> **`#11
> /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(136):
> StubObject->__call(string, array)`**

> ```

> #12
> /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/PropertyRegistry.php(43):
> SESP\AppFactory->getPropertyDefinitions()

> #13
> /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(144):
> SESP\PropertyRegistry->register(SMW\PropertyRegistry)

> #14 /var/www/wiki/w/includes/Hooks.php(177):
> SESP\HookRegistry->SESP\{closure}(SMW\PropertyRegistry)

> #15 /var/www/wiki/w/includes/Hooks.php(205): Hooks::callHook(string, array,
> array, NULL)

> #16
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/PropertyRegistry.php(507):
> Hooks::run(string, array)

> #17
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/PropertyRegistry.php(98):
> SMW\PropertyRegistry->initProperties(array)

> #18
> /var/www/wiki/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(94):
> SMW\PropertyRegistry::getInstance()

> #19
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/DataItemFactory.php(45):
> SMW\DIProperty->__construct(string, boolean)

> #20
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/Property/Annotators/EditProtectedPropertyAnnotator.php(71):
> SMW\DataItemFactory->newDIProperty(string)

> #21
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(208):
> SMW\Property\Annotators\EditProtectedPropertyAnnotator->addTopIndicatorTo(ParserOutput)

> #22
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(170):
> SMW\MediaWiki\Hooks\ParserAfterTidy->addPropertyAnnotations(SMW\Property\AnnotatorFactory,
> SMW\SemanticData)

> #23
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(96):
> SMW\MediaWiki\Hooks\ParserAfterTidy->performUpdate(string)

> #24
> /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(359):
> SMW\MediaWiki\Hooks\ParserAfterTidy->process(string)

> #25 /var/www/wiki/w/includes/Hooks.php(177):
> SMW\MediaWiki\Hooks->onParserAfterTidy(Parser, string)

> #26 /var/www/wiki/w/includes/Hooks.php(205): Hooks::callHook(string, array,
> array, NULL)

> #27 /var/www/wiki/w/includes/parser/Parser.php(1428): Hooks::run(string,
> array)

> #28 /var/www/wiki/w/includes/parser/Parser.php(446):
> Parser->internalParseHalfParsed(string, boolean, boolean)

> #29 /var/www/wiki/w/includes/cache/MessageCache.php(1162):
> Parser->parse(string, Title, ParserOptions, boolean)

> #30 /var/www/wiki/w/includes/Message.php(1244): MessageCache->parse(string,
> Title, boolean, boolean, Language)

> #31 /var/www/wiki/w/includes/Message.php(869): Message->parseText(string)

> #32 /var/www/wiki/w/includes/Message.php(922): Message->toString(string)

> #33
> /var/www/wiki/w/extensions/VisualEditor/includes/VisualEditorDataModule.php(30):
> Message->parse()

> #34 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(706):
> VisualEditorDataModule->getScript(DerivativeResourceLoaderContext)

> #35 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(674):
> ResourceLoaderModule->buildContent(DerivativeResourceLoaderContext)

> #36 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(828):
> ResourceLoaderModule->getModuleContent(DerivativeResourceLoaderContext)

> #37 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(665):
> ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)

> #38 [internal function]: ResourceLoader->{closure}(string)

> #39 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(678):
> array_map(Closure, array)

> #40
> /var/www/wiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(449):
> ResourceLoader->getCombinedVersion(DerivativeResourceLoaderContext, array)

> #41
> /var/www/wiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(422):
> ResourceLoaderStartUpModule->getAllModuleHashes(DerivativeResourceLoaderContext)

> #42 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(831):
> ResourceLoaderStartUpModule->getDefinitionSummary(DerivativeResourceLoaderContext)

> #43 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(665):
> ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)

> #44 [internal function]: ResourceLoader->{closure}(string)

> #45 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(678):
> array_map(Closure, array)

> #46 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(759):
> ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)

> #47 /var/www/wiki/w/load.php(51):
> ResourceLoader->respond(ResourceLoaderContext)

> #48 {main}

> ```

>

>

> --

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/129

From f30ac15945af80ec48ba3e7631f1270064bd509f Mon Sep 17 00:00:00 2001
From: mwjames <jamesin.hongkong.1@gmail.com>
Date: Mon, 11 Nov 2019 23:32:14 +0900
Subject: Check for `wgFullyInitialised`, `MW_NO_SESSION`


diff --git a/src/MediaWiki/Hooks.php b/src/MediaWiki/Hooks.php
index 96d814129..5e06b32cf 100644
--- a/src/MediaWiki/Hooks.php
+++ b/src/MediaWiki/Hooks.php
@@ -339,11 +339,8 @@ class Hooks {
 			Site::isCommandLineMode()
 		);
 
-		// #3341
-		// When running as part of the install don't try to access the DB
-		// or update the Store
-		$parserAfterTidy->isReadOnly(
-			Site::isBlocked()
+		$parserAfterTidy->isReady(
+			Site::isReady()
 		);
 
 		$parserAfterTidy->setLogger(
@@ -805,11 +802,8 @@ class Hooks {
 			 $applicationFactory->getMediaWikiLogger()
 		);
 
-		// #3341
-		// When running as part of the install don't try to access the DB
-		// or update the Store
-		$linksUpdateConstructed->isReadOnly(
-			Site::isBlocked()
+		$linksUpdateConstructed->isReady(
+			Site::isReady()
 		);
 
 		$linksUpdateConstructed->process( $linksUpdate );
diff --git a/src/MediaWiki/Hooks/LinksUpdateConstructed.php b/src/MediaWiki/Hooks/LinksUpdateConstructed.php
index 4b7a090ab..3553d4520 100644
--- a/src/MediaWiki/Hooks/LinksUpdateConstructed.php
+++ b/src/MediaWiki/Hooks/LinksUpdateConstructed.php
@@ -35,7 +35,7 @@ class LinksUpdateConstructed extends HookHandler {
 	/**
 	 * @var boolean
 	 */
-	private $isReadOnly = false;
+	private $isReady = true;
 
 	/**
 	 * @since 3.0
@@ -49,10 +49,10 @@ class LinksUpdateConstructed extends HookHandler {
 	/**
 	 * @since 3.0
 	 *
-	 * @param boolean $isReadOnly
+	 * @param boolean $isReady
 	 */
-	public function isReadOnly( $isReadOnly ) {
-		$this->isReadOnly = (bool)$isReadOnly;
+	public function isReady( $isReady ) {
+		$this->isReady = (bool)$isReady;
 	}
 
 	/**
@@ -71,8 +71,8 @@ class LinksUpdateConstructed extends HookHandler {
 	 */
 	public function process( LinksUpdate $linksUpdate ) {
 
-		if ( $this->isReadOnly ) {
-			return false;
+		if ( $this->isReady === false ) {
+			return $this->doAbort();
 		}
 
 		$title = $linksUpdate->getTitle();
@@ -163,4 +163,13 @@ class LinksUpdateConstructed extends HookHandler {
 		return $parserOutput->mSMWData;
 	}
 
+	private function doAbort() {
+
+		$this->logger->info(
+			"LinksUpdateConstructed was invoked but the site isn't ready yet, aborting the processing."
+		);
+
+		return false;
+	}
+
 }
diff --git a/src/MediaWiki/Hooks/ParserAfterTidy.php b/src/MediaWiki/Hooks/ParserAfterTidy.php
index 91b42e857..33d17cb96 100644
--- a/src/MediaWiki/Hooks/ParserAfterTidy.php
+++ b/src/MediaWiki/Hooks/ParserAfterTidy.php
@@ -48,7 +48,7 @@ class ParserAfterTidy extends HookHandler {
 	/**
 	 * @var boolean
 	 */
-	private $isReadOnly = false;
+	private $isReady = true;
 
 	/**
 	 * @since  1.9
@@ -77,10 +77,10 @@ class ParserAfterTidy extends HookHandler {
 	/**
 	 * @since 3.0
 	 *
-	 * @param boolean $isReadOnly
+	 * @param boolean $isReady
 	 */
-	public function isReadOnly( $isReadOnly ) {
-		$this->isReadOnly = (bool)$isReadOnly;
+	public function isReady( $isReady ) {
+		$this->isReady = (bool)$isReady;
 	}
 
 	/**
@@ -103,8 +103,8 @@ class ParserAfterTidy extends HookHandler {
 
 		// #2432 avoid access to the DBLoadBalancer while being in readOnly mode
 		// when for example Title::isProtected is accessed
-		if ( $this->isReadOnly ) {
-			return false;
+		if ( $this->isReady === false ) {
+			return $this->doAbort();
 		}
 
 		$title = $this->parser->getTitle();
@@ -290,4 +290,13 @@ class ParserAfterTidy extends HookHandler {
 		}
 	}
 
+	private function doAbort() {
+
+		$this->logger->info(
+			"ParserAfterTidy was invoked but the site isn't ready yet, aborting the processing."
+		);
+
+		return false;
+	}
+
 }
diff --git a/src/Site.php b/src/Site.php
index ec687d520..74f0bff5d 100644
--- a/src/Site.php
+++ b/src/Site.php
@@ -33,12 +33,25 @@ class Site {
 	}
 
 	/**
-	 * @since 3.0
+	 * @since 3.2
 	 *
 	 * @return boolean
 	 */
-	public static function isBlocked() {
-		return defined( 'MEDIAWIKI_INSTALL' ) && MEDIAWIKI_INSTALL;
+	public static function isReady() {
+
+		// #3341
+		// When running as part of the install don't try to access the DB
+		// or update the Store
+		if ( defined( 'MEDIAWIKI_INSTALL' ) && MEDIAWIKI_INSTALL ) {
+			return false;
+		}
+
+		// Don't run any parsing or registration when the system isn't full
+		// initialized also prevent issues like "... BadMethodCallException from
+		// ... SessionManager.php Sessions are disabled for this entry point ..."
+		//
+		// https://github.com/wikimedia/mediawiki/blob/cdb7d53dcbb5af884d0d475e255730e35760489b/includes/user/User.php#L293-L317
+		return !defined( 'MW_NO_SESSION' ) && $GLOBALS['wgFullyInitialised'];
 	}
 
 	/**
diff --git a/tests/phpunit/Unit/MediaWiki/Hooks/LinksUpdateConstructedTest.php b/tests/phpunit/Unit/MediaWiki/Hooks/LinksUpdateConstructedTest.php
index e3cae2077..e11995004 100644
--- a/tests/phpunit/Unit/MediaWiki/Hooks/LinksUpdateConstructedTest.php
+++ b/tests/phpunit/Unit/MediaWiki/Hooks/LinksUpdateConstructedTest.php
@@ -21,11 +21,13 @@ class LinksUpdateConstructedTest extends \PHPUnit_Framework_TestCase {
 
 	private $testEnvironment;
 	private $namespaceExaminer;
+	private $spyLogger;
 
 	protected function setUp() {
 		parent::setUp();
 
 		$this->testEnvironment = new TestEnvironment();
+		$this->spyLogger = $this->testEnvironment->newSpyLogger();
 
 		$this->namespaceExaminer = $this->getMockBuilder( '\SMW\NamespaceExaminer' )
 			->disableOriginalConstructor()
@@ -119,7 +121,7 @@ class LinksUpdateConstructedTest extends \PHPUnit_Framework_TestCase {
 			$this->namespaceExaminer
 		);
 
-		$instance->setLogger( $this->testEnvironment->newSpyLogger() );
+		$instance->setLogger( $this->spyLogger );
 		$instance->disableDeferredUpdate();
 
 		$this->assertTrue(
@@ -219,7 +221,7 @@ class LinksUpdateConstructedTest extends \PHPUnit_Framework_TestCase {
 		);
 	}
 
-	public function testIsReadOnly_DoNothing() {
+	public function testIsNotReady_DoNothing() {
 
 		$linksUpdate = $this->getMockBuilder( '\LinksUpdate' )
 			->disableOriginalConstructor()
@@ -232,7 +234,9 @@ class LinksUpdateConstructedTest extends \PHPUnit_Framework_TestCase {
 			$this->namespaceExaminer
 		);
 
-		$instance->isReadOnly( true );
+		$instance->setLogger( $this->spyLogger );
+
+		$instance->isReady( false );
 
 		$this->assertFalse(
 			$instance->process( $linksUpdate )
diff --git a/tests/phpunit/Unit/MediaWiki/Hooks/ParserAfterTidyTest.php b/tests/phpunit/Unit/MediaWiki/Hooks/ParserAfterTidyTest.php
index f1786d265..f3482d0aa 100644
--- a/tests/phpunit/Unit/MediaWiki/Hooks/ParserAfterTidyTest.php
+++ b/tests/phpunit/Unit/MediaWiki/Hooks/ParserAfterTidyTest.php
@@ -79,7 +79,7 @@ class ParserAfterTidyTest extends \PHPUnit_Framework_TestCase {
 		);
 	}
 
-	public function testIsReadOnly() {
+	public function testIsNotReady_DoNothing() {
 
 		$this->parser->expects( $this->never() )
 			->method( 'getTitle' );
@@ -90,7 +90,9 @@ class ParserAfterTidyTest extends \PHPUnit_Framework_TestCase {
 			$this->cache
 		);
 
-		$instance->isReadOnly( true );
+		$instance->setLogger( $this->spyLogger );
+
+		$instance->isReady( false );
 
 		$text = '';
 		$instance->process( $text );
diff --git a/tests/phpunit/Unit/SiteTest.php b/tests/phpunit/Unit/SiteTest.php
index 6a0d92d1f..611e0c0a8 100644
--- a/tests/phpunit/Unit/SiteTest.php
+++ b/tests/phpunit/Unit/SiteTest.php
@@ -23,11 +23,11 @@ class SiteTest extends \PHPUnit_Framework_TestCase {
 		);
 	}
 
-	public function testIsBlocked() {
+	public function testIsReady() {
 
 		$this->assertInternalType(
 			'boolean',
-			Site::isBlocked()
+			Site::isReady()
 		);
 	}

**Comment by mwjames** [comment]
Expected to be solved by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4400 (see comment).

**Comment by alex-mashin** [comment]
Under SMW 3.1.3, MW 1.34.0 the glossary popups are back.

**Comment by kghbln** [comment]
> Under SMW 3.1.3, MW 1.34.0 the glossary popups are back.

I guess because the fix will be served with 3.2.0. Could you point to an example on sandbox. Currently I do not find "black beauty".

**Comment by alex-mashin** [comment]
It seems that I closed this bug too early, because I confused it with a bug in Semantic Glossary. The error is still observed under MW 1.34.2, SESP 2.0.0. SMW 3.1.3.

```
[c66501a48df2cf3bbf04a5ee] /w/load.php?lang=ru&modules=startup&only=scripts&raw=1&skin=timeless   BadMethodCallException from line 826 of /var/www/wiki/w/includes/session/SessionManager.php: Sessions are disabled for this entry point
Backtrace:
#0 /var/www/wiki/w/includes/session/SessionManager.php(196): MediaWiki\Session\SessionManager->getSessionFromInfo()
#1 /var/www/wiki/w/includes/WebRequest.php(806): MediaWiki\Session\SessionManager->getSessionForRequest()
#2 /var/www/wiki/w/includes/user/User.php(1299): WebRequest->getSession()
#3 /var/www/wiki/w/includes/user/User.php(374): User->loadFromSession()
#4 /var/www/wiki/w/includes/user/User.php(5130): User->load()
#5 /var/www/wiki/w/includes/user/User.php(2966): User->loadOptions()
#6 /var/www/wiki/w/includes/context/RequestContext.php(344): User->getOption()
#7 /var/www/wiki/w/includes/StubUserLang.php(52): RequestContext->getLanguage()
#8 /var/www/wiki/w/includes/StubObject.php(168): StubUserLang->_newObject()
#9 /var/www/wiki/w/includes/StubObject.php(111): StubObject->_unstub()
#10 /var/www/wiki/w/includes/StubObject.php(138): StubObject->_call()
#11 /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(136): StubObject->__call()
#12 /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/PropertyRegistry.php(43): SESP\AppFactory->getPropertyDefinitions()
#13 /var/www/wiki/w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(144): SESP\PropertyRegistry->register()
#14 /var/www/wiki/w/includes/Hooks.php(174): SESP\HookRegistry->SESP\{closure}()
#15 /var/www/wiki/w/includes/Hooks.php(202): Hooks::callHook()
#16 /var/www/wiki/w/extensions/SemanticMediaWiki/src/PropertyRegistry.php(507): Hooks::run()
#17 /var/www/wiki/w/extensions/SemanticMediaWiki/src/PropertyRegistry.php(98): SMW\PropertyRegistry->initProperties()
#18 /var/www/wiki/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(94): SMW\PropertyRegistry::getInstance()
#19 /var/www/wiki/w/extensions/SemanticMediaWiki/src/DataItemFactory.php(45): SMW\DIProperty->__construct()
#20 /var/www/wiki/w/extensions/SemanticMediaWiki/src/Property/Annotators/EditProtectedPropertyAnnotator.php(71): SMW\DataItemFactory->newDIProperty()
#21 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(208): SMW\Property\Annotators\EditProtectedPropertyAnnotator->addTopIndicatorTo()
#22 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(169): SMW\MediaWiki\Hooks\ParserAfterTidy->addPropertyAnnotations()
#23 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(96): SMW\MediaWiki\Hooks\ParserAfterTidy->performUpdate()
#24 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(359): SMW\MediaWiki\Hooks\ParserAfterTidy->process()
#25 /var/www/wiki/w/includes/Hooks.php(174): SMW\MediaWiki\Hooks->onParserAfterTidy()
#26 /var/www/wiki/w/includes/Hooks.php(202): Hooks::callHook()
#27 /var/www/wiki/w/includes/parser/Parser.php(1617): Hooks::run()
#28 /var/www/wiki/w/includes/parser/Parser.php(596): Parser->internalParseHalfParsed()
#29 /var/www/wiki/w/includes/cache/MessageCache.php(1243): Parser->parse()
#30 /var/www/wiki/w/includes/language/Message.php(1251): MessageCache->parse()
#31 /var/www/wiki/w/includes/language/Message.php(879): Message->parseText()
#32 /var/www/wiki/w/includes/language/Message.php(932): Message->toString()
#33 /var/www/wiki/w/extensions/VisualEditor/includes/VisualEditorDataModule.php(30): Message->parse()
#34 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(719): VisualEditorDataModule->getScript()
#35 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(687): ResourceLoaderModule->buildContent()
#36 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(822): ResourceLoaderModule->getModuleContent()
#37 /var/www/wiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(283): ResourceLoaderModule->getVersionHash()
#38 /var/www/wiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(468): ResourceLoaderStartUpModule->getModuleRegistrations()
#39 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(719): ResourceLoaderStartUpModule->getScript()
#40 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(687): ResourceLoaderModule->buildContent()
#41 /var/www/wiki/w/includes/resourceloader/ResourceLoaderModule.php(822): ResourceLoaderModule->getModuleContent()
#42 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(665): ResourceLoaderModule->getVersionHash()
#43 [internal function]: ResourceLoader->{closure}()
#44 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(677): array_map()
#45 /var/www/wiki/w/includes/resourceloader/ResourceLoader.php(764): ResourceLoader->getCombinedVersion()
#46 /var/www/wiki/w/load.php(48): ResourceLoader->respond()
#47 {main}
```

**Comment by kghbln** [comment]
> It seems that I closed this bug too early, because I confused it with a bug in Semantic Glossary. The error is still observed under MW 1.34.2, SESP 2.0.0. SMW 3.1.3.

I guess because the fix will be served with 3.2.0. Could you point to an example on sandbox. Currently I do not find "black beauty".

**Comment by alex-mashin** [comment]
I applied the patch https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4400/files manually and the error went away.

> Currently I do not find "black beauty".
What do you mean by the "black beauty"?

**Comment by kghbln** [comment]
> What do you mean by the "black beauty"?

Didn't you say that the popups or so went black because of this reason. Could also be that I misread something somewhere.

> I applied the patch https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4400/files manually and the error went away.

Thanks for testing. Probably worth back-porting. I will ask.

**Comment by alex-mashin** [comment]
> > What do you mean by the "black beauty"?
> Didn't you say that the popups or so went black because of this reason. Could also be that I misread something somewhere.
Semantic glossary normally produces popups, which used to be black, if I remember correctly; and they disappeared due to some other bug that I confused with this one. That bug is now corrected: I applied the patch manually as well.
