### ISSUE TITLE
Add special property to track the page length

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#74]
I need a special property that allows me to track the length of a page (`_PAGELGTH`) to be able to track pages of extraordinary size or to track which pages exceed an expected length of x bytes. This will help in wiki gardening efforts.

I guess this may be implemented similarily to the (`_PAGEID`) special property.

**Comment by kghbln** [comment]
@mwjames Will this be possible by just imitating [L165](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/src/Annotator/ExtraPropertyAnnotator.php#L165) and [L261](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/src/Annotator/ExtraPropertyAnnotator.php#L261)

**Comment by mwjames** [comment]
> @mwjames Will this be possible by just imitating L165 and L261?

Yes this will work for 1.*, yet due to the request I created #75 which also includes https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/refact-v2/docs/01-extension.md.

This is not going to be finished this weekend and even then its needs extensive hand-to-hand testing since I changed everything so that each piece can be tested individually. 

It also requires https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2493 otherwise it creates some odd tables.

**Comment by kghbln** [comment]
Wow, I surely and unintentional triggered something here.

> It also requires SemanticMediaWiki/SemanticMediaWiki#2493 otherwise it creates some odd tables.

Since this pull is meant to be served with SMW 3.0.0 ...

> Yes this will work for 1.*

... we could still do a SESP 1.5.0 bringing this and to ...

> This is not going to be finished this weekend and even then its needs extensive hand-to-hand testing since I changed everything so that each piece can be tested individually.

... have a good chunk of time testing it.

**Comment by mwjames** [comment]
> Since this pull is meant to be served with SMW 3.0.0 ...

Back-ported relate SMW change to 2.5.x, knowing that 3.0 is going to be faraway.

> ... we could still do a SESP 1.5.0 bringing this and to ...

If you throw in a PR, sure!

**Comment by kghbln** [comment]
@mwjames Thanks a bunch for tweaking my effort. The field test shows that it works perfect. Will release on Tuesday as 1.5.0!
